default: &default
  adapter: 'postgresql'
  encoding: 'utf-8'
  pool: 5
  host: '192.168.0.XX'
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  schema_search_path: 'votaprato'

development:
  <<: *default
  database: 'cristiane_estudo'
  port: 5432
